### ISSUE TITLE
Setting month tracker for habit streaks done in Tasks plugin

### ISSUE THREAD

**Issue by Zataghni** [pyrochlore/obsidian-tracker#213]
I've been cracking my brain trying to set this one up, but I can't quite do it so I'm asking for a suggestion on how to implement this or as a feature if it's not possible at the current version of the plugin.

I want to setup a **month** tracker to display the streak of a **recurring task** _within a single note_, with the x dataset being pulled from **each recurrence's done date** and the y dataset as true or false. An added bonus would be displaying whether or not a task's done date corresponds to it's due date.

To set up a habit task, I'm using the Tasks plugin to create a recurring task within a file named after a habit item. For instance, here's how a habit note looks like in my vault: 

>---
>title: Practice drawing
>tags: [" #habits "]
>type: habit
>---
>>[!info]- Data
>>Related: [[Drawing]
>
># History:
>- [ ] #action Practice drawing #habit 🔁 every day when done 🛫 2023-03-12
>- [x] #action Practice drawing #habit 🔁 every day when done 🛫 2023-03-11 ✅ 2023-03-11
>- [x] #action Practice drawing #habit 🔁 every day when done 🛫 2023-03-10 ✅ 2023-03-10
>- [x] #action Practice drawing #habit 🔁 every day when done 🛫 2023-03-06 ✅ 2023-03-09 

The **done dates** are signaled by the ✅ emoji. 

I would share my attempts if I hadn't erased them out of frustration, so I'm posting this as an open question to see if someone has tried to setup a similar tracking in their vaults.

Thank you in advance for sharing your thoughts on this!

**Comment by anpalcactus** [comment]
Well, that is very much desired feature for me as well.
So far, only tried to use this kind of construction to parse the date from the specific task:

```tracker
searchType: task.done, text
searchTarget: 'text #test 🔁 every day 📅 (?<value>([0-9]{4})-([0-9]{2})-([0-9]{2})), dataviewTarget'
xDataset: 0
folder: Задачи/Привычки
line:
    title: Dataview Inline Field
    fillGap: true
```

For this set of tasks hoarded in the note:
```
- [ ] text #test 🔁 every day 📅 2023-08-15
- [x] text #test 🔁 every day 📅 2023-08-14 ✅ 2023-08-13
- [x] text #test 🔁 every day 📅 2023-08-13 ✅ 2023-08-13
```

But it only seems to grab THE FIRST OCCURENCE IN THE FILE only. Hence the screenshots (p.s. random title is because the code is taken from example):
![image](https://github.com/pyrochlore/obsidian-tracker/assets/61033274/978bfead-4dd7-46a6-a845-1c80deb5c096)
![image](https://github.com/pyrochlore/obsidian-tracker/assets/61033274/4c110586-8244-40ee-9748-be1c69c846da)

@pyrochlore is there any way to make the plug-in look for all of the occurrences in the file? Then it’s probably gonna solve this case
