### ISSUE TITLE
Can obsidian-tracker work with obsidian-tasks?

### ISSUE THREAD

**Issue by shihtiy-tw** [pyrochlore/obsidian-tracker#71]
Hi,

I have been using this plugin "obsidian-tasks" for a while and I will use filter to get all the tasks from different notes to my daily notes.

For example, I will use the following method to filter out my undone tasks in my daily note:

```
  ```tasks
  not done
  due on 2021-09-14
  is not recurring
  ```
```

Recently, I found this great plugin and I want to record my daily tasks with charts.

However, after play around "obsidian-tracker", I found that it will find the task in daily note while I use "obsidian-tasks" to filter tasks from other notes to my daily notes and thus "obsidian-tracker" cannot find the tasks from my daily notes.

Does anyone try similar method? How do you make these two plugins work together?

Thanks!

**Comment by pyrochlore** [comment]
You can still have a Tracker in daily notes collecting tasks from the notes where real tasks reside.

If you can share few samples to me, I can make simple demo for you.

**Comment by shihtiy-tw** [comment]
Hi @pyrochlore,

Thank you for checking this issue and provide the answer.

Really look forward to the filtering function for obsidian-tracker.

**Comment by cogscides** [comment]
This is how habits looks in [Life-Disciplines-Projects](https://github.com/uwidev/life-disciplines-projects).
- [ ] #task [Morning] Floss Teeth 🔁 every day 📅 2021-10-30
- [x] #task [Morning] Floss Teeth 🔁 every day 📅 2021-10-29 ✅ 2021-10-29
- [x] #task [Morning] Floss Teeth 🔁 every day 📅 2021-10-28 ✅ 2021-10-28

I think it will be incredible to connect tracker with tasks! Maybe it's possible to use [dataview API](https://blacksmithgu.github.io/obsidian-dataview/data-annotation/#field-shorthands) as it can annotate inline tasks and understand common Tasks metadata.

**Comment by psarras** [comment]
I would especially like to use this with the calendar view. Maybe even create something like the [theme system journal](https://www.themesystem.com/)?

<img width="394" alt="image" src="https://user-images.githubusercontent.com/3820417/150782133-234ea18f-0821-4906-a5ad-85e87184857e.png">
